apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-gateway
  template:
    metadata:
      labels:
        app: server-gateway
    spec:
      containers:
        - name: server-gateway
          image: server-gateway-image:latest
          ports:
            - containerPort: 8000
