pipeline {
    agent none
    stages {
        stage('Compile') {
            agent {
                docker {
                    image 'maven:3.8.3-openjdk-17' 
                    args '-v /root/.m2:/root/.m2' 
                }
            }
            steps {
                dir('service-product') {
                    sh "mvn clean compile"
                }
            }
        }
        stage('Unit Test') {
            agent {
                docker {
                    image 'maven:3.8.3-openjdk-17' 
                    args '-v /root/.m2:/root/.m2' 
                }
            }
            steps {
                dir('service-product') {
                    sh "mvn test"
                }
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.8.3-openjdk-17' 
                    args '-v /root/.m2:/root/.m2' 
                }
            }
            steps {
                dir('service-product') {
                    sh "mvn -B -DskipTests clean package"
                }
            }
        }
        stage('Deploy') {
            agent any
            steps {
                dir('service-product') {
                    sh "docker ps -f name=service-product -q | xargs --no-run-if-empty docker container stop"
                    sh "docker container ls -a -fname=service-product -q | xargs -r docker container rm"
                    sh "docker images -qa service-product:latest | xargs --no-run-if-empty docker rmi"
                    sh "docker build -t service-product:latest ."
                    sh "docker run -m 300m --name service-product -d -p 4002:4002 service-product -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
                }
            }
        }
    }
}