pipeline {
  agent none
  stages {
    stage('Compile') {
      agent {
        docker {
          image 'maven:3.8.3-openjdk-17' 
          args '-v /root/.m2:/root/.m2' 
        }
      }
      steps {
        dir('service-customer') {
          sh "mvn clean compile"
        }
      }
    }
    stage('Unit Test') {
      agent {
        docker {
          image 'maven:3.8.3-openjdk-17' 
          args '-v /root/.m2:/root/.m2' 
        }
      }
      steps {
        dir('service-customer') {
          sh "mvn test"
        }
      }
    }
    stage('Build') {
      agent {
        docker {
          image 'maven:3.8.3-openjdk-17' 
          args '-v /root/.m2:/root/.m2' 
        }
      }
      steps {
        dir('service-customer') {
          sh "mvn -B -DskipTests clean package"
        }
      }
    }
    stage('Dockerize') {
      steps {
        sh 'docker build -t service-customer-image .'
      }
    }
    stage('Push to Docker') {
      steps {
        sh 'docker push your-docker-image'
      }
    }
    stage('Deploy') {
      steps {
        sh 'kubectl apply -f deployment.yaml'
        sh 'kubectl apply -f service.yaml'
      }
    }
  }
}