pipeline {
    agent none
    stages {
        stage('Compile') {
            agent {
                docker {
                    image 'maven:3.8.3-openjdk-17' 
                    args '-v /root/.m2:/root/.m2' 
                }
            }
            steps {
                dir('master-fraud') {
                    sh "mvn clean compile"
                }
            }
        }
        stage('Unit Test') {
            agent {
                docker {
                    image 'maven:3.8.3-openjdk-17' 
                    args '-v /root/.m2:/root/.m2' 
                }
            }
            steps {
                dir('master-fraud') {
                    sh "mvn test"
                }
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.8.3-openjdk-17' 
                    args '-v /root/.m2:/root/.m2' 
                }
            }
            steps {
                dir('master-fraud') {
                    sh "mvn -B -DskipTests clean package"
                }
            }
        }
        stage('Deploy') {
            agent any
            steps {
                dir('master-fraud') {
                    sh "docker ps -f name=wtrack-master-fraud -q | xargs --no-run-if-empty docker container stop"
                    sh "docker container ls -a -fname=wtrack-master-fraud -q | xargs -r docker container rm"
                    sh "docker images -qa wtrack-master-fraud:latest | xargs --no-run-if-empty docker rmi"
                    sh "docker build -t wtrack-master-fraud:latest ."
                    sh "docker run -m 300m --name wtrack-master-fraud -d -p 4029:4029 -v /data/wdn/wtrack/wtrack-core/master-fraud/logs:/logs wtrack-master-fraud -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
                }
            }
        }
    }
}